theme: jekyll-theme-midnight

title: Unhyped AI - A Sociotechnical & Responsible AI Seminar Series
description: a sociotechnical & responsible AI seminar series

tagline: understanding AI and its effects on society
