theme: jekyll-theme-midnight

title: Unhyped AI - Sociotechnical & Responsible AI Seminars
description: a sociotechnical & responsible AI seminar series

tagline: understanding AI and its effects on society
